# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import embedding_pb2 as embedding__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class GraphEmbeddingServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.predictHead = channel.unary_unary(
        '/com.ices.sh.embedding.rpc.GraphEmbeddingService/predictHead',
        request_serializer=embedding__pb2.PredictHeadRequest.SerializeToString,
        response_deserializer=embedding__pb2.PredictPartResponse.FromString,
        )
    self.predictTail = channel.unary_unary(
        '/com.ices.sh.embedding.rpc.GraphEmbeddingService/predictTail',
        request_serializer=embedding__pb2.PredictTailRequest.SerializeToString,
        response_deserializer=embedding__pb2.PredictPartResponse.FromString,
        )
    self.predictRelation = channel.unary_unary(
        '/com.ices.sh.embedding.rpc.GraphEmbeddingService/predictRelation',
        request_serializer=embedding__pb2.PredictRelationRequest.SerializeToString,
        response_deserializer=embedding__pb2.PredictPartResponse.FromString,
        )
    self.predictTriple = channel.unary_unary(
        '/com.ices.sh.embedding.rpc.GraphEmbeddingService/predictTriple',
        request_serializer=embedding__pb2.PredictTripleRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.getEntityEmbedding = channel.unary_unary(
        '/com.ices.sh.embedding.rpc.GraphEmbeddingService/getEntityEmbedding',
        request_serializer=embedding__pb2.GetEmbeddingRequest.SerializeToString,
        response_deserializer=embedding__pb2.GetEmbeddingResponse.FromString,
        )
    self.getRelationEmbedding = channel.unary_unary(
        '/com.ices.sh.embedding.rpc.GraphEmbeddingService/getRelationEmbedding',
        request_serializer=embedding__pb2.GetEmbeddingRequest.SerializeToString,
        response_deserializer=embedding__pb2.GetEmbeddingResponse.FromString,
        )


class GraphEmbeddingServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def predictHead(self, request, context):
    """预测头实体
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def predictTail(self, request, context):
    """预测尾实体
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def predictRelation(self, request, context):
    """预测关系类型
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def predictTriple(self, request, context):
    """预测三元组是否正确
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getEntityEmbedding(self, request, context):
    """获取实体embedding
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getRelationEmbedding(self, request, context):
    """获取关系embedding
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GraphEmbeddingServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'predictHead': grpc.unary_unary_rpc_method_handler(
          servicer.predictHead,
          request_deserializer=embedding__pb2.PredictHeadRequest.FromString,
          response_serializer=embedding__pb2.PredictPartResponse.SerializeToString,
      ),
      'predictTail': grpc.unary_unary_rpc_method_handler(
          servicer.predictTail,
          request_deserializer=embedding__pb2.PredictTailRequest.FromString,
          response_serializer=embedding__pb2.PredictPartResponse.SerializeToString,
      ),
      'predictRelation': grpc.unary_unary_rpc_method_handler(
          servicer.predictRelation,
          request_deserializer=embedding__pb2.PredictRelationRequest.FromString,
          response_serializer=embedding__pb2.PredictPartResponse.SerializeToString,
      ),
      'predictTriple': grpc.unary_unary_rpc_method_handler(
          servicer.predictTriple,
          request_deserializer=embedding__pb2.PredictTripleRequest.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'getEntityEmbedding': grpc.unary_unary_rpc_method_handler(
          servicer.getEntityEmbedding,
          request_deserializer=embedding__pb2.GetEmbeddingRequest.FromString,
          response_serializer=embedding__pb2.GetEmbeddingResponse.SerializeToString,
      ),
      'getRelationEmbedding': grpc.unary_unary_rpc_method_handler(
          servicer.getRelationEmbedding,
          request_deserializer=embedding__pb2.GetEmbeddingRequest.FromString,
          response_serializer=embedding__pb2.GetEmbeddingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.ices.sh.embedding.rpc.GraphEmbeddingService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
